### ISSUE TITLE
Create a sample page and server to test upload and download with the extension

### ISSUE THREAD

**Issue by b24repo** [k8-proxy/chrome-extension#3]
Create a sample page that upload/downloads some data to a dummy server (Express/Flask simple dummy)

**Comment by kumarsudhish** [comment]
Verified this task by running the codebase on local shared by @gmuditdce and observed that on running the server the upload page is getting loaded and also the extension is get uploaded in the chrome extension.

![image](https://user-images.githubusercontent.com/71662255/94598682-edab7780-02ac-11eb-9546-3ca511a95f1e.png)
![image](https://user-images.githubusercontent.com/71662255/94598698-f439ef00-02ac-11eb-957c-5809baa64225.png)
![image](https://user-images.githubusercontent.com/71662255/94598722-fdc35700-02ac-11eb-911d-857a34dc9a65.png)


Hence the upload page is working fine.
